// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import doscg "github.com/tkhamsila/backendtest/src/domains/doscg"
import mock "github.com/stretchr/testify/mock"

// MapService is an autogenerated mock type for the MapService type
type MapService struct {
	mock.Mock
}

// GetDirectionAPI provides a mock function with given fields: start, destination
func (_m *MapService) GetDirectionAPI(start string, destination string) (*doscg.DirectionResp, error) {
	ret := _m.Called(start, destination)

	var r0 *doscg.DirectionResp
	if rf, ok := ret.Get(0).(func(string, string) *doscg.DirectionResp); ok {
		r0 = rf(start, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*doscg.DirectionResp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(start, destination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
